version: '3'
services:

## APP SERVICES
  app-client:
    image: app-client:latest
    container_name: app-client
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"

  app-server:
    image: app-server:latest
    container_name: app-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081"