version: '3'
services:

## APP SERVICES
  app-client:
    image: app-client:0.0.1-SNAPSHOT
    container_name: app-client
    ports:
      - "8080:8080"
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
    depends_on:
    - fluent-bit

  app-server:
    image: app-server:0.0.1-SNAPSHOT
    container_name: app-server
    ports:
      - "8080"
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
    depends_on:
    - fluent-bit

## GRAFANA SERVICES
  grafana:
    image: "grafana/grafana:latest"
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password
    ports:
    - "3000:3000"
    volumes:
    - './observability/grafana/data:/var/lib/grafana'

  prometheus:
    image: "prom/prometheus:latest"
    container_name: prometheus
    ports:
    - "9090:9090"
    volumes:
    - './observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
    - './observability/prometheus/data:/prometheus'

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
    - './observability/loki:/mnt/config'

#  promtail:
#    image: grafana/promtail:2.9.0
#    container_name: promtail
#    command: -config.file=/etc/promtail/config.yml
#    volumes:
#    - './observability/promtail:/mnt/config'
#    depends_on:
#    - loki

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:2.6.1-amd64
    container_name: fluent-bit
    ports:
      - "24224:24224"
      - "2020:2020"
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./observability/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./observability/tempo/tempo.yaml:/etc/tempo.yaml
      - ./observability/tempo/data:/tmp/tempo
    ports:
#      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
#      - "9095:9095" # tempo grpc
#      - "4317:4317"  # otlp grpc
      - "4318"  # otlp http
#      - "9411:9411"   # zipkin
    depends_on:
    - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector:0.86.0
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./observability/otel-collector/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
 #     - "1888:1888"   # pprof extension
 #     - "8888:8888"   # Prometheus metrics exposed by the collector
 #     - "8889:8889"   # Prometheus exporter metrics
 #     - "13133:13133" # health_check extension
 #     - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # UI
      - "4318"        # OTLP http receiver
    depends_on:
    - otel-collector